/**
 * @license
 * Copyright 2021 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';
export * from '@tensorflow/tfjs-converter';

//backend = webgl
export * from '@tensorflow/tfjs-backend-webgl/dist/base';
import {fromPixelsConfig as FromPixels_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FromPixels';
registerKernel(FromPixels_webgl);
import {expandDimsConfig as ExpandDims_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ExpandDims';
registerKernel(ExpandDims_webgl);
import {cropAndResizeConfig as CropAndResize_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/CropAndResize';
registerKernel(CropAndResize_webgl);
import {castConfig as Cast_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Cast';
registerKernel(Cast_webgl);
import {unpackConfig as Unpack_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Unpack';
registerKernel(Unpack_webgl);
import {reshapeConfig as Reshape_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Reshape';
registerKernel(Reshape_webgl);
import {subConfig as Sub_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sub';
registerKernel(Sub_webgl);
import {multiplyConfig as Multiply_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Multiply';
registerKernel(Multiply_webgl);
import {fusedConv2DConfig as FusedConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_webgl);
import {fusedDepthwiseConv2DConfig as FusedDepthwiseConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedDepthwiseConv2D';
registerKernel(FusedDepthwiseConv2D_webgl);
import {addConfig as Add_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Add';
registerKernel(Add_webgl);
import {resizeBilinearConfig as ResizeBilinear_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_webgl);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_webgl);
import {sigmoidConfig as Sigmoid_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sigmoid';
registerKernel(Sigmoid_webgl);
import {argMaxConfig as ArgMax_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ArgMax';
registerKernel(ArgMax_webgl);
import {floorDivConfig as FloorDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FloorDiv';
registerKernel(FloorDiv_webgl);
import {packConfig as Pack_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Pack';
registerKernel(Pack_webgl);
import {gatherNdConfig as GatherNd_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/GatherNd';
registerKernel(GatherNd_webgl);
import {squaredDifferenceConfig as SquaredDifference_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/SquaredDifference';
registerKernel(SquaredDifference_webgl);
import {sqrtConfig as Sqrt_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sqrt';
registerKernel(Sqrt_webgl);
import {realDivConfig as RealDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/RealDiv';
registerKernel(RealDiv_webgl);
import {concatConfig as Concat_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Concat';
registerKernel(Concat_webgl);
import {identityConfig as Identity_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Identity';
registerKernel(Identity_webgl);